### PR TITLE
merge upstream

### LINKED ISSUE #4: Please merge knyar / nginx-lua-prometheus for new feat.
I add a feat https://github.com/knyar/nginx-lua-prometheus/pull/114 to knyar / nginx-lua-prometheus.
Can lua-resty-prometheus merge it?

### PR DESCRIPTION
**Pull request by yangxikun**
close #4

### CODE REVIEW

**Comment by membphis** [comment]
@yangxikun you can merge the commits

**Comment by membphis** [comment]
image

**Comment by membphis** [comment]
@moonming please take a look at this PR. do you think we can merge this PR directly?

**Comment by yangxikun** [comment]
Any progress on this MR?

**Review by moonming — APPROVED** [review]

**Comment by moonming** [comment]
@yangxikun merged, and happy new year:)

**Pull request merged**
